### ISSUE TITLE
The active power control regulation of the PST does not give the target flow with DC load flow 

### ISSUE THREAD

**Issue by WalAmeni** [powsybl/powsybl-open-loadflow#1045]
### Describe the current behavior

When the loadflow is running on DC, the tap position of the PST changes, but it does not respect the regulating value in active power control regulation mode.

### Describe the expected behavior

Even with DC loadflow, the tap position of the PST should be optimized to respect the regulating values asked for PST in active powser control regulation mode

### Describe the steps

- Import network with pst 
- Activate regulation with regulationMode to ACTIVE_POWER_CONTROL and targetValue
- Run loadflow on DC
- Check the flows on the lines associated to these pst

**Comment by annetill** [comment]
Fixed by #1052
