### ISSUE TITLE
All kinds of operational limit management

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-open-loadflow#108]
* **Do you want to request a *feature* or report a *bug*?**

A feature.

* **What is the current behavior?**

Operational limits are ignored.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

The final state should consider the operational limits: apparent power limit, active power limits, current limits, voltage limits. 

* **What is the motivation / use case for changing the behavior?**

It is the first step to build a security analysis based on the open-lodaflow.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

IIDM only supports current limits and has to evolve.

**Comment by geofjamg** [comment]
Solved by #313
