### ISSUE TITLE
Default value for parameter `addRatioToLinesWithDifferentNominalVoltageAtBothEnds`

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-open-loadflow#291]
* **Do you want to request a *feature* or report a *bug*?**

A feature.

* **What is the current behavior?**

The default value is `false`.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

For equivalent branch support, it improves power flow results to have this parameter set to `true`. @geofjamg It is a problem to change the default value to `true`?

**Comment by geofjamg** [comment]
Ok for true by default

**Comment by geofjamg** [comment]
Solved by #434
