### ISSUE TITLE
DC security analysis support

### ISSUE THREAD

**Issue by obrix** [powsybl/powsybl-open-loadflow#312]
* **Do you want to request a *feature* or report a *bug*?**

A feature

* **What is the current behavior?**

AC mode is hard coded in security analysis code. 

* **What is the expected behavior?**

DC mode must be supported.

After a first analysis of the code I suggest : 

* Make OpenSecurityAnalysis an abstract class and rename it to AbstractSecurityAnalysis
* Create two new classes extending AbstractSecurityAnalysis : AcSecurityAnalysis and DcSecurityAnalysis.
* All the common code will stay in AbstractSecurityAnalysis, some elements of existing OpenSecurityAnalysis can probably be made more generic.
* Sadly there is no common interface for the two LoadFlowEngine (Ac and Dc) and their parameters, so we are probably going to have to keep more specific code than what could have been. But this could be improved later.

@Hadrien-Godard made a list of useful elements already present in DC sensibility analysis that can be reused for Dc security analysis : 

double CONNECTIVITY_LOSS_THRESHOLD
class ComputedContingencyElement
class PhaseTapChangerContingenciesIndexing
DenseMatrix setReferenceActivePowerFlows
void setAlphas
Set<ComputedContingencyElement> getGroupOfElementsBreakingConnectivity
void fillRhsContingency
DenseMatrix initContingencyRhs
void detectPotentialConnectivityLoss
class ConnectivityAnalysisResult
Map<Set<ComputedContingencyElement>, ConnectivityAnalysisResult> computeConnectivityData
void processConverterStation
Map<LfBus, BusState> applyHvdcLineContingency
DenseMatrix calculateStates

Functions createBranchSensitivityValue, calculateSensitivityValues, calculateContingencySensitivityValues, analyse should also be an inspiration.

All common elements for dc security and sensibility analysis can be placed in an helper class DCAnalysisUtil in util subfolder.

**Comment by geofjamg** [comment]
Solved by #313
