### ISSUE TITLE
Some phase shifter cannot control flows 

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-open-loadflow#457]
* **Do you want to request a *feature* or report a *bug*?**

It could be seen as a bug. In case microgrid base case assembled, we fall in a KLU singular issue when :
- Phase control regulation is ON ;
- We run an AC security analysis with all branches as contingencies.

* **What is the current behavior?**

When loosing one of the transformers (not the phase shifter), I think that the phase shifter cannot control flow because it has not parallel line in order to redispatch flows. So in that case, a connectivity analysis is needed (the loose of the phase shifter will lead to two separate connected component). In that case, phase control should be disabled and keep to initial tap position.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
Solved by #460
