### ISSUE TITLE
Network summary ignores Generators with positive P (absorption)(CGMES sign convention)

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/powsybl-open-loadflow#479]
When a generator acts as a load, the network summary is not using it for summation for total generation or total load.
It is simply ignored from both generation and loading.

**Comment by geofjamg** [comment]
Whatever the generator target p is (positive or negative) it is added to generation sum, so I don't think it could be skipped. 
Could you provide a test case for show the issue?

**Comment by AnkurArohi** [comment]
i checked it again it was a data issue 
Closing this case
