### ISSUE TITLE
New transformer voltage control outerloop

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-open-loadflow#485]
* **Do you want to request a *feature* or report a *bug*?**

We already have two transformer voltage control outerloops. The idea is to test a new one, more simple and inspired from the phase control outerloop for phase shifter in current limiter mode.

* **What is the current behavior?**

We have two outerloops that lead to KLU issues on complex networks. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

In the first NR resolution, the transformer voltage control are disabled. In the first outerloop, for each transformer with voltage control, we compute the difference, at the controlled bus, of the voltage and the target voltage. We also compute the sensitivity of an increase of `rho` on the controlled bus voltage. Depending of the sensitivity value, we compute the best tap position that could reach the target V in the linear approximation. After that, we run again a NR resolution. We recompute the discrepancy between the controlled bus voltage and the target voltage. We can stop, or recompute the sensitivity and rounded at a new tap position. 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
Solved by #522
