### ISSUE TITLE
Switches added to branches to open

### ISSUE THREAD

**Issue by flo-dup** [powsybl/powsybl-open-loadflow#515]
* **Do you want to request a *feature* or report a *bug*?**
Bug or explanation missing

* **What is the current behavior?**
Switches to open are added to branches to open in `PropagatedContingency`

* **What is the expected behavior?**
Either explain why and remove the `WTF????` comment, or do not add the switches

* **What is the motivation / use case for changing the behavior?**
Avoid having a `WTF????` comment

* **Other information** 
Was introduced in the first beta version of security analysis:
https://github.com/powsybl/powsybl-open-loadflow/blob/c5ca68507887adcc8b64dc568e8384217d747075/src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysis.java#L156-L159
And now:
https://github.com/powsybl/powsybl-open-loadflow/blob/01863e55fc0a4a69b5212877f00e89e47980bd89/src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java#L87-L90

**Comment by AnkurArohi** [comment]
Please don't use comments like that 
In general it makes the software not professional

**Comment by geofjamg** [comment]
Not relevant anymore
