### ISSUE TITLE
An algorithm which appends a small resistance (r = 0.005 ohm) between the generators which have different target V but are connected to the same bus

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/powsybl-open-loadflow#535]
* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

Load FLow Error and KLU Issues

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
No KLU issue, no type of bus change 

* **What is the motivation / use case for changing the behavior?**

PV bus type should not be converted to PQ, as we are losing the possibility to let Q freely distribute(calculate)
Reduces the degree of freedom for optimization

* **Please tell us about your environment:**
  - PowSyBl Version: ... 0.20
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
Could you provide a test case for that? I disagree with the solution, if 2 generators try to control voltage of the same bus with a different value, it is just a data issue. In current OLF version we log a warning and use one the the target voltage. How could it be responsible for a KLU issue?

**Comment by AnkurArohi** [comment]
I can agree with you @geofjamg 
I was simply suggesting a manipulation just to go around this data issue

**Comment by AnkurArohi** [comment]
I could not have a test case for this issue at this moment and I see that the powsybl is now considering the control to leave on generator level and not on bus, I think I can close this issue
