### ISSUE TITLE
Support of Reporter in security analysis

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-open-loadflow#554]
* **Do you want to request a *feature* or report a *bug*?**

A feature.

* **What is the current behavior?**

The reporter is set to NO_OP in the implementation of the security analysis.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

Logs must be added.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
Partially done in #576

**Comment by geofjamg** [comment]
I close this issue, if one day we need more logs we will create another one.
