### ISSUE TITLE
SVC reactive limits modeling could be improved

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-open-loadflow#80]
* **Do you want to request a *feature* or report a *bug*?**

More a *feature* about SVC reactive limits.

* **What is the current behavior?**

Currently, minQ and maxQ are defined using Bmin and Bmax and the nominal voltage of the connected bus. It is in fact an approximation.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

In a way, reactive power furniture or reactive power consumption could be over estimated or under estimated using nominal voltage.

* **What is the expected behavior?**

That the limits depend on calculated voltage. 

* **What is the motivation / use case for changing the behavior?**

To have the right reactive limits in order to have the more right power flow solution.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by adriguir** [comment]
The behavior of the Static Var Compensator should be modified so that the QMin and QMax are calculated on the fly during the external loop using BMin * the calculated value of U from the terminal.
