### ISSUE TITLE
Voltage targets in case of controls with different types

### ISSUE THREAD

**Issue by Hadrien-Godard** [powsybl/powsybl-open-loadflow#975]
### Describe the current behavior

In case of several voltage controls with different types (generator, transformer or shunt) present on the same zero-impedance sub-network, only one is applied. If this control is lost after a contingency or action application in the Security Analysis, another type control is applied.

Currently, the voltage target used depends on the control type that is effectively applied, so it may change after the contingency or action application.

### Describe the expected behavior

In case of several voltage controls with different types (generator, transformer or shunt) present on the same zero-impedance sub-network, we still expect that only one is applied. If this control is lost after a contingency or action application in the Security Analysis, another control type should be applied as a replacement as it is done today.

However, we expect that the target voltage of the applied control type is kept at the value of the disabled voltage control type, thus voltage target should not change, except in case of a partition of the zero-impedance sub-network.

### Describe the motivation

This behavior is primarily motivated by the fact that different voltage targets applied on the same zero-impedance sub-network comes from inconsistencies in the input data. In this case, the computation engine must choose which target is kept. Since the choice is arbitrary, we propose to stick to this choice even after an event has disabled the main voltage control.

Furthermore, shifting a bus voltage target by a potential large amount while keeping the same topology might cause non-convergence in the Newton-Raphson algorithm of the Security Analysis. 

Notice also that currently, in case of several generators controlling voltage at the same bus, only one voltage target is kept, even after the generator whose target comes from has been put in contingency.

**Comment by annetill** [comment]
@geofjamg and me are not aligned with this behavior with default parameters. The main argument is that we will have different results in the two following cases :
- We run a load flow after a voltage control disabling in IIDM level (the disabled voltage control will not exist at all in LfNetwork) ;
- We run a security analysis with a contingency that disables the voltage control.

**Comment by Hadrien-Godard** [comment]
Ok. Should we put this new behavior under a new parameter, named for instance: keepVoltageTargetAlignedAfterContingency?

**Comment by annetill** [comment]
> Ok. Should we put this new behavior under a new parameter, named for instance: keepVoltageTargetAlignedAfterContingency?

For me, to be confirmed by @jeandemanged, everything can be managed with the list of string you have introduced with your PR. When nothing is provided as parameter -> default/main behavior

**Comment by jeandemanged** [comment]
@Hadrien-Godard @annetill proposing to close this issue with status "Close as not planned". I had a wrong interpretation of my users requirements. After users confirmation the current powsybl behavior is what we want, nothig different.
Apologies again.

**Comment by Hadrien-Godard** [comment]
> @Hadrien-Godard @annetill proposing to close this issue with status "Close as not planned". I had a wrong interpretation of my users requirements. After users confirmation the current powsybl behavior is what we want, nothing different. Apologies again.

Yes I agree. I am closing it.
